# Generated by Django 5.0.1 on 2025-05-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
